# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MonitorGastos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MonitorGastos
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  target 'MonitorGastosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MonitorGastosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
